export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

type Role = "Admin" | "Editor" | "Contributor" | "Viewer";
type DecisionStatus = "Approved" | "Working Proposal" | "Deprecated" | "Open Question";
type TaskStatus = "Backlog" | "In Progress" | "Review" | "Done";
type TaskPriority = "P0" | "P1" | "P2" | "P3";

export type Database = {
  public: {
    Tables: {
      profiles: { Row: { id: string; name: string; email: string; role: Role; avatar_url: string | null; created_at: string; updated_at: string }; Insert: { id: string; name: string; email: string; role?: Role; avatar_url?: string | null }; Update: { name?: string; email?: string; role?: Role; avatar_url?: string | null }; Relationships: [] };
      handbook_pages: { Row: { id: string; slug: string; title: string; domain: string; status: DecisionStatus; owner_id: string | null; owner_label: string; current_version_id: string | null; tags: string[]; visibility: string; created_by: string | null; created_at: string; updated_at: string }; Insert: { slug: string; title: string; domain: string; status?: DecisionStatus; owner_id?: string | null; owner_label?: string; current_version_id?: string | null; tags?: string[]; visibility?: string; created_by?: string | null }; Update: { title?: string; domain?: string; status?: DecisionStatus; owner_id?: string | null; owner_label?: string; current_version_id?: string | null; tags?: string[]; visibility?: string }; Relationships: [] };
      page_versions: { Row: { id: string; page_id: string; version: string; content: Json; created_by: string | null; author_label: string; created_at: string; change_summary: string; linked_decision_id: string | null }; Insert: { page_id: string; version: string; content: Json; created_by?: string | null; author_label?: string; change_summary: string; linked_decision_id?: string | null }; Update: never; Relationships: [] };
      decisions: { Row: { id: string; decision_code: string; title: string; status: DecisionStatus; canonical_text: string; reason: string; owner_id: string | null; owner_label: string; sources: string[]; decided_at: string; created_by: string | null; created_at: string; updated_at: string }; Insert: { decision_code: string; title: string; status?: DecisionStatus; canonical_text: string; reason: string; owner_id?: string | null; owner_label?: string; sources?: string[]; decided_at?: string; created_by?: string | null }; Update: { title?: string; status?: DecisionStatus; canonical_text?: string; reason?: string; owner_id?: string | null; owner_label?: string; sources?: string[]; decided_at?: string }; Relationships: [] };
      decision_replacements: { Row: { decision_id: string; replaces_decision_id: string; created_at: string; created_by: string | null }; Insert: { decision_id: string; replaces_decision_id: string; created_by?: string | null }; Update: never; Relationships: [] };
      change_entries: { Row: { id: string; object_type: string; object_id: string; change_type: string; what_changed: string; reason: string; before_ref: string | null; after_ref: string | null; linked_decision_id: string | null; author_id: string | null; author_label: string; created_at: string }; Insert: { object_type: string; object_id: string; change_type: string; what_changed: string; reason: string; before_ref?: string | null; after_ref?: string | null; linked_decision_id?: string | null; author_id?: string | null; author_label?: string }; Update: never; Relationships: [] };
      tasks: { Row: { id: string; task_code: string; title: string; owner_id: string | null; owner_label: string; status: TaskStatus; priority: TaskPriority; due_at: string | null; outcome: string | null; created_by: string | null; created_at: string; updated_at: string }; Insert: { task_code: string; title: string; owner_id?: string | null; owner_label?: string; status?: TaskStatus; priority?: TaskPriority; due_at?: string | null; outcome?: string | null; created_by?: string | null }; Update: { title?: string; owner_id?: string | null; owner_label?: string; status?: TaskStatus; priority?: TaskPriority; due_at?: string | null; outcome?: string | null }; Relationships: [] };
      flows: { Row: { id: string; flow_code: string; title: string; description: string; mermaid_source: string; status: "Draft" | "Published"; owner_id: string | null; owner_label: string; created_by: string | null; created_at: string; updated_at: string }; Insert: { flow_code: string; title: string; description?: string; mermaid_source: string; status?: "Draft" | "Published"; owner_id?: string | null; owner_label?: string; created_by?: string | null }; Update: { title?: string; description?: string; mermaid_source?: string; status?: "Draft" | "Published"; owner_id?: string | null; owner_label?: string }; Relationships: [] };
      comments: { Row: { id: string; object_type: string; object_id: string; body: string; author_id: string; created_at: string; resolved_at: string | null; archived_at: string | null }; Insert: { object_type: string; object_id: string; body: string; author_id: string }; Update: { resolved_at?: string | null; archived_at?: string | null }; Relationships: [] };
      object_links: { Row: { id: string; source_type: string; source_id: string; target_type: string; target_id: string; relation_type: string; created_at: string; created_by: string | null }; Insert: { source_type: string; source_id: string; target_type: string; target_id: string; relation_type: string; created_by?: string | null }; Update: never; Relationships: [] };
      glossary_terms: { Row: { id: string; term: string; definition: string; status: DecisionStatus; deprecated_aliases: string[]; linked_decision_id: string | null; created_by: string | null; created_at: string; updated_at: string }; Insert: { term: string; definition: string; status?: DecisionStatus; deprecated_aliases?: string[]; linked_decision_id?: string | null; created_by?: string | null }; Update: { term?: string; definition?: string; status?: DecisionStatus; deprecated_aliases?: string[]; linked_decision_id?: string | null }; Relationships: [] };
      audit_events: { Row: { id: number; actor_id: string | null; action: string; object_type: string; object_id: string; metadata: Json; created_at: string }; Insert: never; Update: never; Relationships: [] };
      search_documents: { Row: { id: string; object_type: string; object_id: string; title: string; body: string; status: string; owner_label: string; domain: string; route: string; historical: boolean; updated_at: string; search_vector: unknown }; Insert: never; Update: never; Relationships: [] };
    };
    Views: { [key: string]: never };
    Functions: {
      search_workspace: { Args: { search_query: string; type_filter?: string | null; status_filter?: string | null; owner_filter?: string | null; domain_filter?: string | null }; Returns: { object_type: string; object_id: string; title: string; status: string; owner_label: string; domain: string; route: string; historical: boolean; snippet: string; rank: number }[] };
      save_handbook_revision: { Args: { page_slug: string; revision_content: Json; revision_summary: string; decision_code?: string | null }; Returns: string };
    };
    Enums: { user_role: Role; decision_status: DecisionStatus; task_status: TaskStatus; task_priority: TaskPriority };
    CompositeTypes: { [key: string]: never };
  };
};
