export type Json=string|number|boolean|null|{[key:string]:Json|undefined}|Json[];
export type Database={public:{Tables:{
 profiles:{Row:{id:string;name:string;email:string;role:"Admin"|"Editor"|"Contributor"|"Viewer";avatar_url:string|null;created_at:string;updated_at:string};Insert:{id:string;name:string;email:string;role?:"Admin"|"Editor"|"Contributor"|"Viewer";avatar_url?:string|null};Update:{name?:string;email?:string;role?:"Admin"|"Editor"|"Contributor"|"Viewer";avatar_url?:string|null}};
 handbook_pages:{Row:{id:string;slug:string;title:string;domain:string;status:string;owner_id:string|null;owner_label:string;current_version_id:string|null;tags:string[];created_at:string;updated_at:string};Insert:{slug:string;title:string;domain:string;status?:string;owner_id?:string|null;owner_label?:string;tags?:string[]};Update:{title?:string;domain?:string;status?:string;owner_id?:string|null;owner_label?:string;current_version_id?:string|null;tags?:string[]}};
 page_versions:{Row:{id:string;page_id:string;version:string;content:Json;created_by:string|null;author_label:string;created_at:string;change_summary:string;linked_decision_id:string|null};Insert:{page_id:string;version:string;content:Json;created_by?:string|null;author_label?:string;change_summary:string;linked_decision_id?:string|null};Update:never};
 decisions:{Row:{id:string;decision_code:string;title:string;status:string;canonical_text:string;reason:string;owner_id:string|null;owner_label:string;sources:string[];decided_at:string;created_at:string;updated_at:string};Insert:{decision_code:string;title:string;status?:string;canonical_text:string;reason:string;owner_id?:string|null;owner_label?:string;sources?:string[]};Update:{title?:string;status?:string;canonical_text?:string;reason?:string;owner_id?:string|null;owner_label?:string;sources?:string[]}};
 tasks:{Row:{id:string;task_code:string;title:string;owner_id:string|null;owner_label:string;status:string;priority:string;due_at:string|null;outcome:string|null;created_at:string;updated_at:string};Insert:{task_code:string;title:string;owner_id?:string|null;owner_label?:string;status?:string;priority?:string;due_at?:string|null;outcome?:string|null};Update:{title?:string;owner_id?:string|null;owner_label?:string;status?:string;priority?:string;due_at?:string|null;outcome?:string|null}};
 flows:{Row:{id:string;flow_code:string;title:string;description:string;mermaid_source:string;status:string;owner_id:string|null;owner_label:string;created_at:string;updated_at:string};Insert:{flow_code:string;title:string;description?:string;mermaid_source:string;status?:string;owner_id?:string|null;owner_label?:string};Update:{title?:string;description?:string;mermaid_source?:string;status?:string;owner_id?:string|null;owner_label?:string}};
 comments:{Row:{id:string;object_type:string;object_id:string;body:string;author_id:string;created_at:string;resolved_at:string|null;archived_at:string|null};Insert:{object_type:string;object_id:string;body:string;author_id:string};Update:{resolved_at?:string|null;archived_at?:string|null}};
 object_links:{Row:{id:string;source_type:string;source_id:string;target_type:string;target_id:string;relation_type:string;created_at:string;created_by:string|null};Insert:{source_type:string;source_id:string;target_type:string;target_id:string;relation_type:string;created_by?:string|null};Update:never};
 [key:string]:{Row:Record<string,unknown>;Insert:Record<string,unknown>;Update:Record<string,unknown>};
};Views:{[key:string]:never};Functions:{search_workspace:{Args:{search_query:string;type_filter?:string|null;status_filter?:string|null;owner_filter?:string|null;domain_filter?:string|null};Returns:{object_type:string;object_id:string;title:string;status:string;owner_label:string;domain:string;route:string;historical:boolean;snippet:string;rank:number}[]}};Enums:{user_role:"Admin"|"Editor"|"Contributor"|"Viewer"};CompositeTypes:{[key:string]:never}}}

