"use server";
import { revalidatePath } from "next/cache";import { z } from "zod";import { createClient } from "@/lib/supabase/server";

const commentSchema=z.object({objectType:z.enum(["handbook","decision","task","flow"]),objectId:z.string().min(3).max(100),body:z.string().trim().min(1).max(4000)});
const taskSchema=z.object({taskCode:z.string().regex(/^TASK-\d{3,}$/),title:z.string().min(3).max(180),ownerLabel:z.string().min(1).max(100),status:z.enum(["Backlog","In Progress","Review","Done"]),priority:z.enum(["P0","P1","P2","P3"]),dueAt:z.string().optional(),outcome:z.string().max(2000).optional()});
const flowSchema=z.object({flowCode:z.string().regex(/^FLOW-\d{3,}$/),title:z.string().min(3).max(180),description:z.string().max(1000),mermaidSource:z.string().min(8).max(30000),status:z.enum(["Draft","Published"])});
const decisionSchema=z.object({decisionCode:z.string().regex(/^DEC-\d{3,}$/),title:z.string().min(3).max(180),status:z.enum(["Approved","Working Proposal","Deprecated","Open Question"]),canonicalText:z.string().min(10).max(10000),reason:z.string().min(10).max(10000),ownerLabel:z.string().min(1).max(100)});

async function authed(){const supabase=await createClient();const {data,error}=await supabase.auth.getUser();if(error||!data.user)throw new Error("Authentication required");return {supabase,user:data.user}}
export async function createComment(input:z.input<typeof commentSchema>){const value=commentSchema.parse(input);const {supabase,user}=await authed();const {error}=await supabase.from("comments").insert({object_type:value.objectType,object_id:value.objectId,body:value.body,author_id:user.id} as never);if(error)throw error;revalidatePath("/", "layout")}
export async function upsertTask(input:z.input<typeof taskSchema>){const v=taskSchema.parse(input);const {supabase}=await authed();const {error}=await supabase.from("tasks").upsert({task_code:v.taskCode,title:v.title,owner_label:v.ownerLabel,status:v.status,priority:v.priority,due_at:v.dueAt||null,outcome:v.outcome||null} as never,{onConflict:"task_code"});if(error)throw error;revalidatePath("/tasks")}
export async function upsertFlow(input:z.input<typeof flowSchema>){const v=flowSchema.parse(input);const {supabase}=await authed();const {error}=await supabase.from("flows").upsert({flow_code:v.flowCode,title:v.title,description:v.description,mermaid_source:v.mermaidSource,status:v.status} as never,{onConflict:"flow_code"});if(error)throw error;revalidatePath("/flows")}
export async function upsertDecision(input:z.input<typeof decisionSchema>){const v=decisionSchema.parse(input);const {supabase}=await authed();const {error}=await supabase.from("decisions").upsert({decision_code:v.decisionCode,title:v.title,status:v.status,canonical_text:v.canonicalText,reason:v.reason,owner_label:v.ownerLabel} as never,{onConflict:"decision_code"});if(error)throw error;revalidatePath("/decisions")}
