"use client";

import Link from "next/link";
import { useState, useTransition } from "react";
import { createChange } from "@/app/actions";
import type { Change } from "@/lib/types";

export function ChangesView({ changes }: { changes: Change[] }) {
  const [creating, setCreating] = useState(false); const [pending, startTransition] = useTransition(); const [message, setMessage] = useState("");
  return <section className="panel panel-pad"><div className="row space"><div className="tabs"><span className="tab active">All changes</span><span className="tab">Documents</span><span className="tab">Decisions</span><span className="tab">Flows</span><span className="tab">Tasks</span></div><button className="btn mint-btn" onClick={() => setCreating((value) => !value)}>+ New change</button></div>{creating && <form className="list-item stack mutation-form" style={{ marginBottom: 14 }} onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); startTransition(async () => { try { await createChange({ objectType: String(data.get("objectType")), objectId: String(data.get("objectId")), changeType: String(data.get("changeType")) as Change["type"], whatChanged: String(data.get("whatChanged")), reason: String(data.get("reason")), beforeRef: String(data.get("beforeRef") ?? ""), afterRef: String(data.get("afterRef") ?? ""), decisionCode: String(data.get("decisionCode") ?? "") }); setCreating(false); setMessage("Change entry saved."); } catch { setMessage("Unable to save change entry."); } }); }}><div className="editor-fields"><select name="changeType" className="select">{["document", "decision", "flow", "task", "system"].map((type) => <option key={type}>{type}</option>)}</select><input name="objectType" className="input" placeholder="Object type" required/><input name="objectId" className="input" placeholder="Object ID" required/><input name="decisionCode" className="input" placeholder="DEC-### (optional)"/><input name="beforeRef" className="input" placeholder="Previous state"/><input name="afterRef" className="input" placeholder="New state"/></div><input name="whatChanged" className="input" placeholder="What changed" required/><textarea name="reason" className="textarea compact" placeholder="Why it changed" required/><button className="btn mint-btn" disabled={pending}>{pending ? "Saving…" : "Save change entry"}</button></form>}{message && <p className="tiny mint">{message}</p>}<table className="table"><thead><tr><th>Date / time</th><th>Type</th><th>Object</th><th>What changed</th><th>Why</th><th>Before → After</th><th>Decision</th></tr></thead><tbody>{changes.map((change) => <tr key={change.id}><td>{change.at}</td><td><span className="badge">{change.type}</span></td><td>{change.object}</td><td><strong>{change.what}</strong></td><td>{change.why}</td><td>{change.before} → {change.after}</td><td>{change.decision === "—" ? "—" : <Link className="link" href={`/decisions/${change.decision}`}>{change.decision}</Link>}</td></tr>)}</tbody></table></section>;
}
