"use client";

import Link from "next/link";
import { useState, useTransition } from "react";
import { upsertDecision } from "@/app/actions";
import type { Change, Decision } from "@/lib/types";
import { StatusBadge } from "./status-badge";

const filters = ["All", "Approved", "Working Proposal", "Deprecated", "Open Question"] as const;

export function DecisionEditor({ decision, onDone }: { decision?: Decision; onDone?: () => void }) {
  const [pending, startTransition] = useTransition(); const [message, setMessage] = useState("");
  return <form className="stack mutation-form" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); startTransition(async () => { try { await upsertDecision({ decisionCode: String(data.get("decisionCode")), title: String(data.get("title")), status: String(data.get("status")) as Decision["status"], canonicalText: String(data.get("canonicalText")), reason: String(data.get("reason")), ownerLabel: String(data.get("ownerLabel")), sources: String(data.get("sources") ?? "") }); setMessage("Decision saved to Postgres."); onDone?.(); } catch { setMessage("Unable to save decision."); } }); }}><div className="editor-fields"><input name="decisionCode" className="input" defaultValue={decision?.id} placeholder="DEC-###" required/><input name="title" className="input" defaultValue={decision?.title} placeholder="Decision title" required/><select name="status" className="select" defaultValue={decision?.status ?? "Working Proposal"}>{filters.slice(1).map((status) => <option key={status}>{status}</option>)}</select><input name="ownerLabel" className="input" defaultValue={decision?.owner ?? "Core"} placeholder="Owner" required/></div><textarea name="canonicalText" className="textarea" defaultValue={decision?.canonical} placeholder="Canonical decision" required/><textarea name="reason" className="textarea compact" defaultValue={decision?.reason} placeholder="Reason" required/><input name="sources" className="input" defaultValue={decision?.sources.join(", ")} placeholder="Sources, comma separated"/><div className="row"><button className="btn mint-btn" disabled={pending}>{pending ? "Saving…" : "Save decision"}</button>{message && <span className="tiny muted">{message}</span>}</div></form>;
}

export function DecisionsView({ decisions, changes }: { decisions: Decision[]; changes: Change[] }) {
  const [filter, setFilter] = useState<(typeof filters)[number]>("All"); const [q, setQ] = useState(""); const [creating, setCreating] = useState(false);
  const rows = decisions.filter((decision) => (filter === "All" || decision.status === filter) && decision.title.toLowerCase().includes(q.toLowerCase()));
  return <div className="grid-main-wide"><section className="panel panel-pad"><div className="row space"><div className="tabs">{filters.map((value) => <button className={`tab ${value === filter ? "active" : ""}`} onClick={() => setFilter(value)} key={value}>{value}</button>)}</div><div className="row"><input className="input" value={q} onChange={(event) => setQ(event.target.value)} placeholder="Search decisions…"/><button className="btn mint-btn" onClick={() => setCreating((value) => !value)}>+ New decision</button></div></div>{creating && <div className="list-item" style={{ marginBottom: 14 }}><DecisionEditor onDone={() => setCreating(false)}/></div>}<table className="table"><thead><tr><th>ID</th><th>Title</th><th>Status</th><th>Owner</th><th>Updated</th><th>Related</th></tr></thead><tbody>{rows.map((decision) => <tr key={decision.id}><td><Link className="link" href={`/decisions/${decision.id}`}>{decision.id}</Link></td><td><strong>{decision.title}</strong></td><td><StatusBadge value={decision.status}/></td><td>{decision.owner}</td><td>{decision.date}</td><td>{decision.related[0] ?? "—"}</td></tr>)}</tbody></table></section><aside className="panel inspector"><h2 className="section-title">Change Log</h2><p className="tiny muted">Chronological changes linked back to decisions.</p><div className="divider"/><div className="timeline">{changes.slice(0, 5).map((change) => <div className="timeline-entry" key={change.id}><span className="tiny muted">{change.at}</span><strong>{change.what}</strong><span className="tiny muted">{change.object}</span></div>)}</div><div className="divider"/>{decisions[0] && <div className="list-item"><strong>{decisions[0].id} · {decisions[0].title}</strong><p className="tiny muted">Why: {decisions[0].reason}</p><div className="row space"><span className="tiny">Replaces <span className="link">{decisions[0].replaces ?? "—"}</span></span><StatusBadge value={decisions[0].status}/></div></div>}</aside></div>;
}
