"use client";

import Link from "next/link";
import { useState, useTransition } from "react";
import { upsertFlow } from "@/app/actions";
import type { Comment, Flow } from "@/lib/types";
import { Comments } from "./comments";
import { MermaidDiagram } from "./mermaid-diagram";
import { StatusBadge } from "./status-badge";

export function FlowsView({ flows, comments, initialId = "FLOW-001" }: { flows: Flow[]; comments: Comment[]; initialId?: string }) {
  const flow = flows.find((item) => item.id === initialId) ?? flows[0]; const [source, setSource] = useState(flow?.mermaid ?? "flowchart TD\n A[No flow selected]"); const [tab, setTab] = useState<"diagram" | "source">("diagram"); const [pending, startTransition] = useTransition(); const [message, setMessage] = useState("");
  if (!flow) return <div className="panel empty">No flows found.</div>;
  return <><div className="flow-list">{flows.map((item) => <Link href={`/flows/${item.id}`} className={`flow-chip ${item.id === flow.id ? "active" : ""}`} key={item.id}>{item.title}</Link>)}</div><div className="flow-layout"><section className="panel flow-canvas"><div className="row space"><div className="row"><h2 className="section-title" style={{ margin: 0 }}>{flow.title}</h2><StatusBadge value={flow.status}/></div><div className="row"><span className="tiny muted">{message}</span><button className="btn mint-btn" disabled={pending} onClick={() => startTransition(async () => { try { await upsertFlow({ flowCode: flow.id, title: flow.title, description: flow.description, mermaidSource: source, status: flow.status, ownerLabel: flow.owner }); setMessage("Saved to Postgres."); } catch { setMessage("Unable to save flow."); } })}>{pending ? "Saving…" : "Save version"}</button></div></div><div className="tabs" style={{ marginTop: 8 }}><button className={`tab ${tab === "source" ? "active" : ""}`} onClick={() => setTab("source")}>Mermaid source</button><button className={`tab ${tab === "diagram" ? "active" : ""}`} onClick={() => setTab("diagram")}>Diagram</button></div>{tab === "diagram" ? <div className="diagram-wrap"><MermaidDiagram source={source}/></div> : <div className="editor-grid"><textarea className="textarea" value={source} onChange={(event) => setSource(event.target.value)} aria-label="Mermaid source"/><div className="diagram-wrap"><MermaidDiagram source={source}/></div></div>}</section><aside className="panel inspector"><h2 className="section-title">Flow Context</h2><p className="muted tiny">{flow.description}</p><div className="divider"/><div className="meta-grid"><span className="muted">Stable ID</span><span>{flow.id}</span><span className="muted">Owner</span><span>{flow.owner}</span><span className="muted">Updated</span><span>{flow.updated}</span><span className="muted">Status</span><StatusBadge value={flow.status}/></div><div className="divider"/><h3 className="section-title">Related objects</h3><div className="stack">{flow.related.map((id) => <Link className="list-item link" href={id.startsWith("DEC") ? `/decisions/${id}` : id.startsWith("TASK") ? `/tasks/${id}` : `/handbook/${id}`} key={id}>{id}</Link>)}</div><div className="divider"/><Comments objectType="flow" objectId={flow.id} comments={comments.filter((comment) => comment.objectId === flow.id)}/></aside></div></>;
}
