"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import type { SearchResult } from "@/lib/types";
import { StatusBadge } from "./status-badge";

const types = ["all", "handbook", "decision", "change", "task", "flow", "comment", "version", "glossary"] as const;

export function SearchPage() {
  const [q, setQ] = useState(""); const [type, setType] = useState<(typeof types)[number]>("all"); const [status, setStatus] = useState(""); const [owner, setOwner] = useState(""); const [domain, setDomain] = useState(""); const [results, setResults] = useState<SearchResult[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { const controller = new AbortController(); const timer = window.setTimeout(async () => { setLoading(true); const params = new URLSearchParams({ q, type }); if (status) params.set("status", status); if (owner) params.set("owner", owner); if (domain) params.set("domain", domain); try { const response = await fetch(`/api/search?${params}`, { signal: controller.signal }); const body = await response.json(); setResults(body.results ?? []); } catch { if (!controller.signal.aborted) setResults([]); } finally { if (!controller.signal.aborted) setLoading(false); } }, 180); return () => { window.clearTimeout(timer); controller.abort(); }; }, [q, type, status, owner, domain]);
  return <><input autoFocus className="input" style={{ fontSize: 16, padding: 14, marginBottom: 16 }} value={q} onChange={(event) => setQ(event.target.value)} placeholder="Search canonical knowledge, decisions, changes, tasks, flows, comments, and versions…"/><div className="search-layout"><aside className="panel filters"><h3 className="section-title">Filters</h3><label className="tiny muted">Type</label><select className="select" value={type} onChange={(event) => setType(event.target.value as typeof type)}>{types.map((value) => <option key={value} value={value}>{value}</option>)}</select><div className="divider"/><label className="tiny muted">Status</label><select className="select" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All statuses</option><option>Approved</option><option>Working Proposal</option><option>Open Question</option><option>Deprecated</option><option>Published</option><option>Historical</option></select><label className="tiny muted" style={{ display: "block", marginTop: 12 }}>Owner</label><input className="input" value={owner} onChange={(event) => setOwner(event.target.value)} placeholder="All owners"/><label className="tiny muted" style={{ display: "block", marginTop: 12 }}>Domain</label><input className="input" value={domain} onChange={(event) => setDomain(event.target.value)} placeholder="All domains"/><div className="divider"/><p className="tiny muted">Ranking: exact title → canonical / approved → glossary / tags → body → comments → history.</p></aside><section className="stack"><div className="row space"><span className="muted">{loading ? "Searching Postgres…" : `${results.length} results`}</span><span className="tiny muted">↑↓ navigate · Enter open · Esc close</span></div>{results.map((result) => <Link href={result.route} className="panel result" key={`${result.type}-${result.id}`}><StatusBadge value={result.type}/><div><div className="row"><h3>{result.title}</h3>{result.historical && <span className="historical">Historical</span>}</div><p>{highlight(result.snippet.slice(0, 220), q)}</p></div><div className="tiny muted"><div>{result.owner}</div><div>{result.domain}</div><div>{result.date}</div></div></Link>)}</section></div></>;
}

function highlight(text: string, query: string) { if (!query) return text; const index = text.toLowerCase().indexOf(query.toLowerCase()); if (index < 0) return text; return <>{text.slice(0, index)}<mark className="mark">{text.slice(index, index + query.length)}</mark>{text.slice(index + query.length)}</>; }
